# Generated by Django 2.0 on 2019-01-03 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=django.utils.timezone.now, max_length=16, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
