# Generated by Django 2.0 on 2019-01-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_perfil_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
    ]
