# Generated by Django 2.0 on 2019-01-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_line', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='titulo',
        ),
    ]
